/* STUDY DZ — CENTURY MODE */
let focusTimerHandle=null, focusSeconds=25*60, focusMode='work', deferredInstallPrompt=null;
const CENTURY_KEY='studydz_century_v1';
function centuryData(){try{return JSON.parse(safeGet(CENTURY_KEY))||{tasks:[],cards:[]};}catch(e){return {tasks:[],cards:[]};}}
function saveCentury(d){safeSet(CENTURY_KEY,JSON.stringify(d));}
function initCenturyTools(){renderTasks(); renderCards(); renderStatsMini();}
function out(html){const el=document.getElementById('toolsOutput');if(el)el.innerHTML=html;}
function openFocusTimer(){
 out(`<div class="focus-box"><div class="focus-ring"><b id="focusClock">25:00</b><small id="focusLabel">جلسة تركيز</small></div><div class="focus-presets"><button onclick="setFocus(25)">25 د</button><button onclick="setFocus(45)">45 د</button><button onclick="setFocus(60)">60 د</button></div><div class="focus-actions"><button class="primary" onclick="toggleFocus()" id="focusToggle">ابدأ ▶</button><button onclick="resetFocus()">إعادة ضبط ↺</button></div><p class="hint">اترك القرآن يعمل في الخلفية وركّز على مادة واحدة حتى تنتهي الجلسة.</p></div>`);
 resetFocus();
}
function setFocus(min){clearInterval(focusTimerHandle);focusSeconds=min*60;focusMode='work';updateFocusUI();}
function updateFocusUI(){const m=String(Math.floor(focusSeconds/60)).padStart(2,'0'),s=String(focusSeconds%60).padStart(2,'0');const c=document.getElementById('focusClock');if(c)c.textContent=`${m}:${s}`;const l=document.getElementById('focusLabel');if(l)l.textContent=focusMode==='work'?'جلسة تركيز':'استراحة قصيرة';}
function toggleFocus(){const btn=document.getElementById('focusToggle');if(focusTimerHandle){clearInterval(focusTimerHandle);focusTimerHandle=null;if(btn)btn.textContent='استمرار ▶';return;}if(focusSeconds<=0)focusSeconds=25*60;if(btn)btn.textContent='إيقاف مؤقت ⏸';focusTimerHandle=setInterval(()=>{focusSeconds--;updateFocusUI();if(focusSeconds<=0){clearInterval(focusTimerHandle);focusTimerHandle=null;focusMode=focusMode==='work'?'break':'work';focusSeconds=focusMode==='work'?25*60:5*60;updateFocusUI();if('Notification' in window&&Notification.permission==='granted')new Notification('Study DZ',{body:focusMode==='break'?'أحسنت! حان وقت الراحة.':'العودة إلى التركيز 🚀'});alert(focusMode==='break'?'أحسنت! حان وقت الراحة ☕':'انتهت الراحة! لنكمل 🚀');}},1000);}
function resetFocus(){clearInterval(focusTimerHandle);focusTimerHandle=null;focusSeconds=25*60;focusMode='work';updateFocusUI();const b=document.getElementById('focusToggle');if(b)b.textContent='ابدأ ▶';}
function openPlanner(){out(`<div class="planner-box"><div class="add-task"><input id="taskInput" placeholder="مثال: مراجعة الرياضيات — الدوال"><select id="taskPriority"><option>عادي</option><option>مهم</option><option>عاجل</option></select><button class="primary" onclick="addStudyTask()">إضافة +</button></div><div id="taskList"></div></div>`);renderTasks();}
function addStudyTask(){const i=document.getElementById('taskInput');if(!i?.value.trim())return;const d=centuryData();d.tasks.unshift({id:Date.now(),text:i.value.trim(),priority:document.getElementById('taskPriority').value,done:false});saveCentury(d);i.value='';renderTasks();}
function renderTasks(){const box=document.getElementById('taskList');if(!box)return;const d=centuryData();box.innerHTML=d.tasks.length?d.tasks.map(t=>`<div class="task ${t.done?'done':''}"><button onclick="toggleTask(${t.id})">${t.done?'✓':'○'}</button><span>${escapeHTML(t.text)}<small>${t.priority}</small></span><button onclick="deleteTask(${t.id})">✕</button></div>`).join(''):'<div class="empty-tool">لا توجد مهام. أضف أول مهمة 👇</div>';}
function toggleTask(id){const d=centuryData(),t=d.tasks.find(x=>x.id===id);if(t)t.done=!t.done;saveCentury(d);renderTasks();renderStatsMini();}
function deleteTask(id){const d=centuryData();d.tasks=d.tasks.filter(x=>x.id!==id);saveCentury(d);renderTasks();}
function openFlashcards(){out(`<div class="flash-box"><div class="add-card"><input id="cardQ" placeholder="السؤال / المصطلح"><textarea id="cardA" placeholder="الإجابة / التعريف"></textarea><button class="primary" onclick="addCard()">حفظ البطاقة 🧠</button></div><div id="cardsList"></div></div>`);renderCards();}
function addCard(){const q=document.getElementById('cardQ'),a=document.getElementById('cardA');if(!q?.value.trim()||!a?.value.trim())return;const d=centuryData();d.cards.unshift({id:Date.now(),q:q.value.trim(),a:a.value.trim(),seen:0});saveCentury(d);q.value='';a.value='';renderCards();}
function renderCards(){const box=document.getElementById('cardsList');if(!box)return;const d=centuryData();box.innerHTML=d.cards.length?d.cards.map(c=>`<button class="flashcard" onclick="this.classList.toggle('flip')"><span class="front">${escapeHTML(c.q)}</span><span class="back">${escapeHTML(c.a)}</span></button>`).join(''):'<div class="empty-tool">أنشئ بطاقاتك الخاصة للمراجعة السريعة.</div>';}
function showStudyStats(){const p=loadProgress(),total=p.history.reduce((a,h)=>a+(h.total||0),0),correct=p.history.reduce((a,h)=>a+(h.correct||0),0),avg=p.history.length?Math.round(p.history.reduce((a,h)=>a+(h.pct||0),0)/p.history.length):0;out(`<div class="stats-dashboard"><div><b>${p.points}</b><small>نقطة</small></div><div><b>${p.history.length}</b><small>امتحان</small></div><div><b>${total?Math.round(correct/total*100):0}%</b><small>دقة الإجابات</small></div><div><b>${p.streak||0} 🔥</b><small>أيام متتالية</small></div><div class="wide"><b>${avg}%</b><small>متوسط النتائج</small><div class="big-meter"><i style="width:${avg}%"></i></div></div></div>`);}
function renderStatsMini(){/* intentionally lightweight */}
function quickSearchStudy(){const q=prompt('ابحث عن قسم أو أداة:');if(!q)return;const map=[['فروض','screen-papers'],['اختبارات','screen-papers'],['قرآن','screen-quran'],['تقدمي','screen-progress'],['أدوات','screen-tools'],['تركيز','screen-tools'],['بطاقات','screen-tools'],['خطة','screen-tools']];const hit=map.find(x=>x[0].includes(q)||q.includes(x[0]));if(hit){showScreen(hit[1]);if(hit[1]==='screen-tools')initCenturyTools();}else alert('لم أجد قسمًا مطابقًا. جرّب: قرآن، فروض، تقدمي، تركيز، بطاقات، خطة.');}
async function installStudyApp(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return;}if('Notification' in window&&Notification.permission==='default')try{await Notification.requestPermission();}catch(e){}alert('إذا كان المتصفح يدعم التثبيت، ستظهر أيقونة التثبيت في شريط العنوان أو قائمة المتصفح.');}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;});
function escapeHTML(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
